project:
  type: website
  output-dir: docs

website:
  title: "alondra-casas-210portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: STAT 210 Portfolio
      - href: stat210-portfolio/portfolio.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
execute:
  echo: false
  message: false
  warning: false

